server:
  port: 12999

anti-shake:
  implement-type: native_redis

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: 'anti-shake-cases'
      paths-to-match: '/**'
      packages-to-scan: com.github.gelald.redis
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: ZH_CN
